### ISSUE TITLE
Async google pings?

### ISSUE THREAD

**Issue by joevandyk** [hybridgroup/gabba#12]
It looks like all the pings to google are synchronous, right? 

It would be nice to have a callback method so client code could specify how they wanted to ping google.

**Comment by inspire22** [comment]
That would require a thread, which would potentially be very dangerous in something like a rails app, which (currently) aren't built for multithreaded concurrency.

**Comment by deadprogram** [comment]
You could create separate evented code that just uses gabba to do work for it, or a worker thread in separate process, or any of a couple of solutions. Seems like closing best for now.
