### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by forrest** [hybridgroup/gabba#21]
Hey,

Just wondering if this is under the MIT licence?

Thanks for the great work,
Forrest

**Comment by deadprogram** [comment]
Hi, Forrest

Yes it is, and we need to add the files to clarify this... thanks for the
reminder!

Regards,
Ron

On Mon, Dec 17, 2012 at 8:32 PM, Forrest Zeisler
notifications@github.comwrote:

> Hey,
> 
> Just wondering if this is under the MIT licence?
> 
> Thanks for the great work,
> Forrest
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hybridgroup/gabba/issues/21.

## 

Ron Evans
The Hybrid Group
http://hybridgroup.com
p. 310-916-9924
m. 310-597-1013

**Comment by forrest** [comment]
Thanks for the quick reponse :-)

**Comment by PikachuEXE** [comment]
You can close this issue now
