### ISSUE TITLE
Easier injection of existing cookie params

### ISSUE THREAD

**Issue by outoftime** [hybridgroup/gabba#3]
Hi there,

I'm using Gabba to power a hand-rolled email open tracking pixel. It's hitting a normal action in our Rails app, so for users in web-based email clients, we have a shot at grabbing their existing Analytics cookie, in particular the `__utma` parameter. It'd be nice if there were a straightforward way to inject this into the Gabba instance, but the best I could come up with was to call `cookie_params`, do a regexp substitution of the `__utma` bit of that, and then set `utmcc` to the result. In particular, I would want to continue using Gabba's randomly-generated `__utmz` parameter, since the referral information contained in the real cookie is bogus.

I'm happy to submit a patch if you'd like!

Mat

**Comment by deadprogram** [comment]
Sorry about the delayed response. Let me take a look at that...
