### ISSUE TITLE
Documentation and setup doubts

### ISSUE THREAD

**Issue by feliperaul** [hybridgroup/gabba#8]
Guys,

This gem seems really interesting to us, specially for server-side e-commerce tracking (this way we avoid problems in thankyou page not loading, loading twice, so on ..).

The thing is, the gem seriously lacks documentation. For example, for e-commerce tracking, I see there's code there, but I have no clue how to call it / implement it.

**Comment by deadprogram** [comment]
Hi, there. You are right, and we'd sure appreciate a pull request with some better docs! Perhaps TomDoc?

**Comment by feliperaul** [comment]
If we could understand what was going on, we would be more then glad to help with the documentation, but so far we're stuck !

Em 28/03/2012, às 12:28, Ron Evans escreveu:

**Comment by deadprogram** [comment]
I just committed some hopefully slightly better docs. You should now have enough to get started, please let me know how it goes.
